CREATE TABLE "clinics" (
	"id" text PRIMARY KEY NOT NULL,
	"name" jsonb NOT NULL,
	"city" text NOT NULL,
	"address" jsonb NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"lat" double precision DEFAULT 0 NOT NULL,
	"lng" double precision DEFAULT 0 NOT NULL,
	"rating" real DEFAULT 0 NOT NULL,
	"reviews" integer DEFAULT 0 NOT NULL,
	"specialties" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"about" jsonb NOT NULL,
	"image_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "doctors" (
	"id" text PRIMARY KEY NOT NULL,
	"clinic_id" text NOT NULL,
	"name" jsonb NOT NULL,
	"specialty" text NOT NULL,
	"title" jsonb NOT NULL,
	"years" integer DEFAULT 0 NOT NULL,
	"fee" integer DEFAULT 0 NOT NULL,
	"room" text DEFAULT '' NOT NULL,
	"bio" jsonb NOT NULL,
	"image_id" text,
	"sort" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "images" (
	"id" text PRIMARY KEY NOT NULL,
	"content_type" text NOT NULL,
	"data" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "doctors" ADD CONSTRAINT "doctors_clinic_id_clinics_id_fk" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "doctors_clinic_idx" ON "doctors" USING btree ("clinic_id");--> statement-breakpoint
-- The sample clinics and doctors the site launched with, so every database starts with them.
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('shifa-family-clinic','{"en":"Shifa Family Clinic","ar":"عيادة الشفاء العائلية","ckb":"کلینیکی خێزانی شیفا"}'::jsonb,'erbil','{"en":"100m Street, Ankawa, Erbil","ar":"شارع 100 متر، عنكاوا، أربيل","ckb":"شەقامی ١٠٠ مەتری، عەنکاوە، هەولێر"}'::jsonb,'07730304703',36.238,43.993,4.8,214,'["general","pediatrics"]'::jsonb,'{"en":"A neighbourhood family practice for adults and children, with same-week appointments.","ar":"عيادة عائلية للكبار والأطفال مع مواعيد خلال الأسبوع نفسه.","ckb":"کلینیکێکی خێزانی بۆ گەورە و منداڵ، بە نۆرە لە هەمان هەفتەدا."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '0 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('azadi-dental-studio','{"en":"Azadi Dental Studio","ar":"استوديو آزادي لطب الأسنان","ckb":"ستۆدیۆی ددانی ئازادی"}'::jsonb,'sulaymaniyah','{"en":"Salim Street, Sulaymaniyah","ar":"شارع سالم، السليمانية","ckb":"شەقامی سالم، سلێمانی"}'::jsonb,'07730304703',35.56,45.433,4.9,341,'["dentistry"]'::jsonb,'{"en":"Check-ups, fillings, and cosmetic dentistry in a calm, modern studio.","ar":"فحوصات وحشوات وتجميل أسنان في عيادة هادئة وحديثة.","ckb":"پشکنین، پڕکردنەوە و جوانکاری ددان لە ستۆدیۆیەکی هێمن و نوێدا."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '1 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('nabd-heart-center','{"en":"Nabd Heart Center","ar":"مركز نبض للقلب","ckb":"سەنتەری دڵی نەبز"}'::jsonb,'baghdad','{"en":"Al-Mansour, Baghdad","ar":"المنصور، بغداد","ckb":"مەنسوور، بەغدا"}'::jsonb,'07730304703',33.317,44.345,4.7,158,'["cardiology","general"]'::jsonb,'{"en":"Heart check-ups, ECG, and follow-up care with experienced cardiologists.","ar":"فحوصات القلب وتخطيط القلب والمتابعة مع أطباء قلب ذوي خبرة.","ckb":"پشکنینی دڵ، ئێ سی جی و چاودێری بەردەوام لەگەڵ پزیشکی دڵی بە ئەزموون."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '2 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('roj-skin-clinic','{"en":"Roj Skin Clinic","ar":"عيادة روژ للجلدية","ckb":"کلینیکی پێستی ڕۆژ"}'::jsonb,'erbil','{"en":"Gulan Street, Erbil","ar":"شارع گولان، أربيل","ckb":"شەقامی گوڵان، هەولێر"}'::jsonb,'07730304703',36.205,44.009,4.6,97,'["dermatology"]'::jsonb,'{"en":"Medical and cosmetic dermatology for all skin types.","ar":"طب الجلدية العلاجي والتجميلي لجميع أنواع البشرة.","ckb":"چارەسەری پزیشکی و جوانکاری پێست بۆ هەموو جۆرە پێستێک."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '3 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('dayik-womens-health','{"en":"Dayik Women’s Health","ar":"دايك لصحة المرأة","ckb":"دایک بۆ تەندروستی ئافرەتان"}'::jsonb,'duhok','{"en":"Kawa Street, Duhok","ar":"شارع كاوا، دهوك","ckb":"شەقامی کاوە، دهۆک"}'::jsonb,'07730304703',36.865,42.988,4.8,186,'["gynecology","pediatrics"]'::jsonb,'{"en":"Women’s health, pregnancy care, and newborn check-ups under one roof.","ar":"صحة المرأة ورعاية الحمل وفحص حديثي الولادة في مكان واحد.","ckb":"تەندروستی ئافرەتان، چاودێری دووگیانی و پشکنینی منداڵی تازە لەدایکبوو لە یەک شوێندا."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '4 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "clinics" ("id","name","city","address","phone","lat","lng","rating","reviews","specialties","about","created_at") VALUES ('chra-eye-and-bone','{"en":"Chra Eye & Bone Clinic","ar":"عيادة چرا للعيون والعظام","ckb":"کلینیکی چرا بۆ چاو و ئێسک"}'::jsonb,'sulaymaniyah','{"en":"Bakhtiari, Sulaymaniyah","ar":"بختياري، السليمانية","ckb":"بەختیاری، سلێمانی"}'::jsonb,'07730304703',35.57,45.405,4.5,73,'["ophthalmology","orthopedics"]'::jsonb,'{"en":"Eye exams, vision care, and joint and bone consultations.","ar":"فحص النظر ورعاية العيون واستشارات العظام والمفاصل.","ckb":"پشکنینی چاو، چاودێری بینین و ڕاوێژی ئێسک و جومگە."}'::jsonb,timestamptz '2026-10-01 00:00:00+00' + interval '5 minutes') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-sara-ahmed','shifa-family-clinic','{"en":"Dr. Sara Ahmed","ar":"د. سارة أحمد","ckb":"د. سارا ئەحمەد"}'::jsonb,'general','{"en":"Family physician","ar":"طبيبة عائلة","ckb":"پزیشکی خێزان"}'::jsonb,12,25000,'1','{"en":"Focuses on preventive care and long-term follow-up for whole families.","ar":"تركّز على الرعاية الوقائية والمتابعة طويلة الأمد للعائلات.","ckb":"سەرنج دەخاتە سەر چاودێری پێشوەختە و بەدواداچوونی درێژخایەن بۆ خێزانەکان."}'::jsonb,0) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-karwan-aziz','shifa-family-clinic','{"en":"Dr. Karwan Aziz","ar":"د. كاروان عزيز","ckb":"د. کاروان عەزیز"}'::jsonb,'pediatrics','{"en":"Pediatrician","ar":"طبيب أطفال","ckb":"پزیشکی منداڵان"}'::jsonb,9,25000,'2','{"en":"Cares for newborns to teenagers, including vaccinations and growth checks.","ar":"يعتني بالأطفال من حديثي الولادة حتى المراهقة، بما في ذلك اللقاحات وفحوص النمو.","ckb":"چاودێری منداڵان دەکات لە تازە لەدایکبووەوە تا هەرزەکاری، لەوانە کوتان و پشکنینی گەشە."}'::jsonb,1) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-hana-rashid','azadi-dental-studio','{"en":"Dr. Hana Rashid","ar":"د. هناء رشيد","ckb":"د. هانا ڕەشید"}'::jsonb,'dentistry','{"en":"Dentist","ar":"طبيبة أسنان","ckb":"پزیشکی ددان"}'::jsonb,8,20000,'A','{"en":"Gentle general dentistry with a special interest in anxious patients.","ar":"طب أسنان عام بلطف مع اهتمام خاص بالمرضى القلقين.","ckb":"ددانسازی گشتی بە نەرمی، بە گرنگییەکی تایبەت بە نەخۆشە دڵەڕاوکێکان."}'::jsonb,2) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-omar-salih','azadi-dental-studio','{"en":"Dr. Omar Salih","ar":"د. عمر صالح","ckb":"د. عومەر ساڵح"}'::jsonb,'dentistry','{"en":"Orthodontist","ar":"أخصائي تقويم الأسنان","ckb":"پسپۆڕی ڕێکخستنی ددان"}'::jsonb,14,30000,'B','{"en":"Braces and clear aligners for children and adults.","ar":"تقويم الأسنان والقوالب الشفافة للأطفال والبالغين.","ckb":"ڕێکخەری ددان و قاڵبی ڕوون بۆ منداڵان و گەورەکان."}'::jsonb,3) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-layla-hassan','nabd-heart-center','{"en":"Dr. Layla Hassan","ar":"د. ليلى حسن","ckb":"د. لەیلا حەسەن"}'::jsonb,'cardiology','{"en":"Cardiologist","ar":"أخصائية قلب","ckb":"پسپۆڕی دڵ"}'::jsonb,18,40000,'3','{"en":"Hypertension, heart rhythm problems, and cardiac follow-up.","ar":"ارتفاع ضغط الدم واضطرابات نظم القلب ومتابعة مرضى القلب.","ckb":"فشاری خوێنی بەرز، تێکچوونی لێدانی دڵ و بەدواداچوونی نەخۆشانی دڵ."}'::jsonb,4) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-yusuf-karim','nabd-heart-center','{"en":"Dr. Yusuf Karim","ar":"د. يوسف كريم","ckb":"د. یووسف کەریم"}'::jsonb,'general','{"en":"Internal medicine","ar":"باطنية","ckb":"نەخۆشییە ناوەکییەکان"}'::jsonb,11,25000,'1','{"en":"Diabetes, cholesterol, and general adult health.","ar":"السكري والكولسترول والصحة العامة للبالغين.","ckb":"شەکرە، کۆلیسترۆڵ و تەندروستی گشتی گەورەکان."}'::jsonb,5) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-nasrin-jalal','roj-skin-clinic','{"en":"Dr. Nasrin Jalal","ar":"د. نسرين جلال","ckb":"د. نەسرین جەلال"}'::jsonb,'dermatology','{"en":"Dermatologist","ar":"أخصائية جلدية","ckb":"پسپۆڕی پێست"}'::jsonb,10,30000,'2','{"en":"Acne, eczema, and skin checks, plus cosmetic treatments.","ar":"حب الشباب والإكزيما وفحص الجلد، إضافة إلى العلاجات التجميلية.","ckb":"زیپکە، ئێگزیما و پشکنینی پێست، لەگەڵ چارەسەری جوانکاری."}'::jsonb,6) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-avin-mustafa','dayik-womens-health','{"en":"Dr. Avin Mustafa","ar":"د. آفين مصطفى","ckb":"د. ئاڤین مستەفا"}'::jsonb,'gynecology','{"en":"Obstetrician and gynecologist","ar":"أخصائية نسائية وتوليد","ckb":"پسپۆڕی ئافرەتان و منداڵبوون"}'::jsonb,15,35000,'1','{"en":"Pregnancy care, ultrasound, and women’s health at every age.","ar":"رعاية الحمل والسونار وصحة المرأة في كل الأعمار.","ckb":"چاودێری دووگیانی، سۆنار و تەندروستی ئافرەتان لە هەموو تەمەنێکدا."}'::jsonb,7) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-rebin-faraj','dayik-womens-health','{"en":"Dr. Rebin Faraj","ar":"د. ريبين فرج","ckb":"د. ڕێبین فەرەج"}'::jsonb,'pediatrics','{"en":"Neonatologist","ar":"أخصائي حديثي الولادة","ckb":"پسپۆڕی منداڵی تازە لەدایکبوو"}'::jsonb,7,25000,'2','{"en":"Newborn check-ups and early childhood care.","ar":"فحص حديثي الولادة ورعاية الطفولة المبكرة.","ckb":"پشکنینی منداڵی تازە لەدایکبوو و چاودێری منداڵی بچووک."}'::jsonb,8) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-dilan-sherwan','chra-eye-and-bone','{"en":"Dr. Dilan Sherwan","ar":"د. ديلان شيروان","ckb":"د. دیلان شێروان"}'::jsonb,'ophthalmology','{"en":"Ophthalmologist","ar":"أخصائي عيون","ckb":"پسپۆڕی چاو"}'::jsonb,13,30000,'1','{"en":"Eye exams, glasses prescriptions, and cataract assessment.","ar":"فحص العيون ووصف النظارات وتقييم الماء الأبيض.","ckb":"پشکنینی چاو، نووسینی چاویلکە و هەڵسەنگاندنی ئاوی سپی."}'::jsonb,9) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "doctors" ("id","clinic_id","name","specialty","title","years","fee","room","bio","sort") VALUES ('dr-bakhtiyar-ali','chra-eye-and-bone','{"en":"Dr. Bakhtiyar Ali","ar":"د. بختيار علي","ckb":"د. بەختیار عەلی"}'::jsonb,'orthopedics','{"en":"Orthopedic surgeon","ar":"جرّاح عظام","ckb":"نەشتەرگەری ئێسک"}'::jsonb,16,35000,'2','{"en":"Back pain, sports injuries, and joint problems.","ar":"آلام الظهر وإصابات الرياضة ومشاكل المفاصل.","ckb":"ئازاری پشت، برینداربوونی وەرزشی و کێشەکانی جومگە."}'::jsonb,10) ON CONFLICT DO NOTHING;
